import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "bn";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations object
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.pricing": "Play & Booking",
    "nav.booking": "Book Now",
    "nav.events": "Birthday & Events",
    "nav.contact": "Contact",
    "nav.bookVisit": "Book Visit",
    
    // Hero Section
    "hero.badge": "Ages 1–10 Years",
    "hero.title1": "Where Kids",
    "hero.learn": "Learn",
    "hero.and": "&",
    "hero.play": "Play",
    "hero.description": "A safe, hygienic, and joyful indoor playground designed for children aged 1–10 years. Let your little ones explore, learn, and make memories in our supervised play environment.",
    "hero.safeEnvironment": "Safe Environment",
    "hero.hourlyPlay": "Hourly Play",
    "hero.viewOptions": "View Play Options",
    "hero.birthdayEvents": "Birthday & Events",
    "hero.learnPlay": "Learn & Play",
    
    // About Section
    "about.label": "About Us",
    "about.title": "A Space Where",
    "about.titleHighlight": "Learning Meets Play",
    "about.description": "At Baby World, we believe that every child deserves a safe, nurturing environment where they can explore, discover, and grow. Our indoor playground is thoughtfully designed to encourage learning through play.",
    "about.adventureZone": "Adventure Zone",
    "about.learningCorner": "Learning Corner",
    "about.creativeSpace": "Creative Space",
    "about.pretendPlay": "Pretend Play",
    "about.safeHygienic": "Safe & Hygienic",
    "about.safeHygienicDesc": "Regular sanitization and child-safe equipment for peace of mind.",
    "about.trainedStaff": "Trained Staff",
    "about.trainedStaffDesc": "Our friendly team ensures supervision and assistance at all times.",
    "about.ageAppropriate": "Age-Appropriate Activities",
    "about.ageAppropriateDesc": "Curated play zones for children aged 1–10 years old.",
    
    // Pricing Section
    "pricing.label": "Play & Pricing",
    "pricing.title": "Simple, Transparent Pricing",
    "pricing.description": "Choose the play option that works best for your family. Each session includes one child and one guardian.",
    "pricing.hourlyPlay": "Hourly Play",
    "pricing.sessionTitle": "1-Hour Play Session",
    "pricing.sessionDesc": "Perfect for a quick visit. Enjoy all play zones with your little one.",
    "pricing.childGuardian": "1 Child + 1 Guardian",
    "pricing.bookSession": "Book Session",
    "pricing.whatsIncluded": "What's Included",
    "pricing.inclusion1": "Access to all play zones",
    "pricing.inclusion2": "Supervised environment",
    "pricing.inclusion3": "Clean & sanitized equipment",
    "pricing.inclusion4": "Comfortable seating for guardians",
    "pricing.inclusion5": "Air-conditioned facility",
    "pricing.walkIn": "Walk-in Available",
    "pricing.physicalTickets": "Physical Tickets",
    "pricing.physicalDesc": "Prefer to pay in person? Physical tickets are available at our reception.",
    "pricing.noBooking": "No advance booking required. Simply walk in during operating hours.",
    "pricing.guidelines": "Play Zone Guidelines",
    "pricing.rule1": "Socks required for all",
    "pricing.rule2": "Hand sanitization on entry",
    "pricing.rule3": "No outside food allowed",
    "pricing.rule4": "Guardian must stay on-site",
    
    // Booking Section
    "booking.label": "Booking",
    "booking.title": "Book Play Time",
    "booking.description": "Select your preferred date and time. Each session is 1 hour.",
    "booking.trustBadge": "Safe play environment for children aged 1–10 years",
    "booking.selectDate": "Select Date",
    "booking.futureDate": "Any future date",
    "booking.selectTime": "Select Time",
    "booking.eachSlot": "Each slot is 1 hour",
    "booking.selectDateFirst": "Please select a date first",
    "booking.selected": "Selected",
    "booking.available": "Available",
    "booking.booked": "Booked",
    "booking.summary": "Booking Summary",
    "booking.date": "Date",
    "booking.time": "Time",
    "booking.ticket": "Ticket",
    "booking.ticketType": "1 Child + 1 Guardian",
    "booking.total": "Total",
    "booking.confirmBooking": "Confirm Booking",
    "booking.selectDateTime": "Select date & time",
    "booking.paymentNote": "Payment system will be added soon.",
    "booking.book": "Book",
    "booking.select": "Select",
    "booking.bookViaWhatsApp": "Book via WhatsApp",
    "booking.whatsappNote": "Clicking the button will send your booking request via WhatsApp",
    "booking.groupBooking": "Group Booking",
    "booking.selectChildren": "Select number of children (1-5)",
    "booking.childrenSelectedLabel": "child(ren) + guardian(s) selected",
    
    // WhatsApp
    "whatsapp.chat": "WhatsApp",
    "whatsapp.chatWithUs": "Chat on WhatsApp",
    
    // Testimonials
    "testimonials.label": "Parent Reviews",
    "testimonials.title": "What Parents Say About Us",
    "testimonials.description": "See why families trust Baby World for their children's playtime and celebrations.",
    "testimonials.parent1.name": "Fatima Rahman",
    "testimonials.parent1.role": "Mother of 2",
    "testimonials.parent1.quote": "Baby World has become our go-to place for weekend fun. The staff is incredibly attentive, and I love how clean everything is. My kids always have a blast!",
    "testimonials.parent2.name": "Kamal Hossain",
    "testimonials.parent2.role": "Father of 1",
    "testimonials.parent2.quote": "We celebrated my daughter's 4th birthday here and it was magical. The team handled everything professionally. The decorations were beautiful and the kids had so much fun!",
    "testimonials.parent3.name": "Nusrat Jahan",
    "testimonials.parent3.role": "Mother of 3",
    "testimonials.parent3.quote": "As a mother of three, I appreciate the age-appropriate play zones. Each of my children finds something they love. The trained staff gives me peace of mind.",
    "testimonials.trustStatement": "Join hundreds of happy families who trust Baby World",
    
    // Events Section (Home page preview)
    "events.label": "Birthday & Events",
    "events.title": "Celebrate Special Moments",
    "events.description": "Create magical memories with a birthday celebration at Baby World. Safe, joyful, and unforgettable experiences await!",
    "events.basicName": "Basic Celebration",
    "events.basicDesc": "Perfect for intimate gatherings with close friends",
    "events.premiumName": "Premium Party",
    "events.premiumDesc": "A memorable celebration with all the extras",
    "events.grandName": "Grand Event",
    "events.grandDesc": "The ultimate birthday experience",
    "events.mostPopular": "Most Popular",
    "events.inquireNow": "Inquire Now",
    "events.feature.2hours": "2 hours private area",
    "events.feature.3hours": "3 hours private area",
    "events.feature.4hours": "4 hours exclusive area",
    "events.feature.basicDecor": "Basic decorations",
    "events.feature.themeDecor": "Theme decorations",
    "events.feature.customTheme": "Custom theme setup",
    "events.feature.playzone": "Play zone access",
    "events.feature.photo": "Photography session",
    "events.feature.proPhoto": "Professional photography",
    "events.feature.host": "Party host assistance",
    "events.feature.entertainment": "Entertainment activities",
    "events.feature.coordinator": "Dedicated party coordinator",
    "events.gallery": "Celebration Moments",
    "events.viewAll": "View All Packages",
    
    // Events Page Gallery
    "eventsPage.gallery.label": "Photo Gallery",
    "eventsPage.gallery.title": "Memories from Our Celebrations",
    "eventsPage.gallery.description": "See the joy and excitement from previous birthday parties hosted at Baby World.",
    "eventsPage.gallery.note": "More photos available upon request",
    "eventsPage.gallery.clickToView": "Click to view fullscreen",
    
    // Events Page (Dedicated)
    "eventsPage.hero.badge": "Birthday & Special Events",
    "eventsPage.hero.title": "Create Unforgettable",
    "eventsPage.hero.titleHighlight": "Celebrations",
    "eventsPage.hero.description": "Give your child a stress-free, memorable birthday celebration at Baby World. Our safe, supervised environment ensures pure joy for kids and peace of mind for parents.",
    "eventsPage.hero.cta1": "Explore Packages",
    "eventsPage.hero.cta2": "Request Booking",
    "eventsPage.packages.label": "Event Packages",
    "eventsPage.packages.title": "Choose Your Celebration Style",
    "eventsPage.packages.description": "Select the perfect package for your child's special day. Each package includes supervised play in our safe, hygienic environment.",
    "eventsPage.packages.duration": "Duration",
    "eventsPage.packages.ageRange": "Ages 1–10 years",
    "eventsPage.packages.selectPackage": "Select Package",
    "eventsPage.packages.selectedPackage": "Selected",
    "eventsPage.packages.startingFrom": "starting",
    "eventsPage.packages.price.basic": "৳5,000",
    "eventsPage.packages.price.premium": "৳8,500",
    "eventsPage.packages.price.grand": "৳15,000",
    "eventsPage.packages.price.custom": "৳20,000+",
    "eventsPage.packages.priceNote": "Final price based on requirements",
    "eventsPage.packages.customName": "Custom Event",
    "eventsPage.packages.customDesc": "Tailored to your unique requirements",
    "eventsPage.packages.feature.5hours": "5+ hours exclusive area",
    "eventsPage.packages.feature.fullCustom": "Fully customized setup",
    "eventsPage.packages.feature.catering": "Catering coordination",
    "eventsPage.packages.feature.vip": "VIP experience",
    "eventsPage.booking.label": "Book Your Event",
    "eventsPage.booking.title": "Request Event Booking",
    "eventsPage.booking.description": "Fill out the form below and our team will contact you to confirm details and availability.",
    "eventsPage.booking.step1": "Event Type",
    "eventsPage.booking.step2": "Package",
    "eventsPage.booking.step3": "Preferred Date",
    "eventsPage.booking.step4": "Child's Age",
    "eventsPage.booking.step5": "Contact Info",
    "eventsPage.booking.eventTypeBirthday": "Birthday Party",
    "eventsPage.booking.eventTypeOther": "Other Event",
    "eventsPage.booking.selectEventType": "What type of event are you planning?",
    "eventsPage.booking.selectPackageStep": "Select your preferred package",
    "eventsPage.booking.selectDateStep": "Choose your preferred date",
    "eventsPage.booking.ageGroup1": "1–3 years",
    "eventsPage.booking.ageGroup2": "4–6 years",
    "eventsPage.booking.ageGroup3": "7–10 years",
    "eventsPage.booking.selectAgeGroup": "Select your child's age group",
    "eventsPage.booking.parentName": "Parent/Guardian Name",
    "eventsPage.booking.parentPhone": "Phone Number",
    "eventsPage.booking.parentNamePlaceholder": "Enter your full name",
    "eventsPage.booking.parentPhonePlaceholder": "Enter your phone number",
    "eventsPage.booking.next": "Next",
    "eventsPage.booking.back": "Back",
    "eventsPage.booking.submit": "Submit Request",
    "eventsPage.booking.submitting": "Submitting...",
    "eventsPage.booking.confirmNote": "Our team will contact you to confirm details",
    "eventsPage.booking.successTitle": "Request Submitted!",
    "eventsPage.booking.successMessage": "Thank you for your interest. Our team will contact you within 24 hours to confirm your event details.",
    "eventsPage.booking.newRequest": "Submit Another Request",
    "eventsPage.trust.title": "Why Celebrate at Baby World?",
    "eventsPage.trust.description": "Your child's safety and happiness are our top priorities.",
    
    // Trust Section
    "trust.label": "Trust & Safety",
    "trust.title": "Your Child's Safety is Our Priority",
    "trust.description": "We understand that as parents, nothing matters more than your child's well-being. That's why we've built Baby World with safety at its core.",
    "trust.safePlay": "Safe Play Environment",
    "trust.safePlayDesc": "Soft, child-friendly equipment with rounded edges and padded surfaces throughout.",
    "trust.trainedStaff": "Trained Staff",
    "trust.trainedStaffDesc": "Our team is trained in child safety and first aid, ensuring supervision at all times.",
    "trust.childFriendly": "Child-Friendly Equipment",
    "trust.childFriendlyDesc": "Age-appropriate play structures designed for children aged 1–10 years.",
    "trust.cleanHygienic": "Clean & Hygienic",
    "trust.cleanHygienicDesc": "Regular sanitization of all equipment and air-conditioned, well-ventilated space.",
    "trust.statement": "\"I can trust this place with my child.\"",
    
    // Contact Section
    "contact.label": "Contact Us",
    "contact.title": "Visit Baby World Today",
    "contact.description": "Have questions? We'd love to hear from you. Reach out via phone, email, or visit us in person.",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.address": "Address",
    "contact.addressLine1": "27/B, Jannat Tower (Lift #3)",
    "contact.addressLine2": "Lalbagh, Dhaka 1211",
    "contact.hours": "Operating Hours",
    "contact.hoursLine1": "Saturday - Thursday: 10:00 AM – 9:00 PM",
    "contact.hoursLine2": "Friday: 3:00 PM – 9:00 PM",
    "contact.getDirections": "Get Directions",
    "contact.mapComingSoon": "Interactive map coming soon",
    "contact.findUs": "Find Us",
    "contact.parking": "Parking",
    "contact.parkingInfo": "Street parking available nearby",
    "contact.publicTransport": "Public Transport",
    "contact.transportInfo": "Near Lalbagh bus stand",
    "contact.landmark": "Landmark",
    "contact.landmarkInfo": "Jannat Tower, near Lalbagh Fort",
    
    // Contact Form
    "contactForm.title": "Send Us a Message",
    "contactForm.whatsappDescription": "Fill out the form and send us a message directly via WhatsApp.",
    "contactForm.name": "Your Name",
    "contactForm.namePlaceholder": "Enter your full name",
    "contactForm.phone": "Phone Number",
    "contactForm.phonePlaceholder": "Enter your phone number",
    "contactForm.email": "Email (Optional)",
    "contactForm.emailPlaceholder": "Enter your email address",
    "contactForm.message": "Your Message",
    "contactForm.messagePlaceholder": "How can we help you?",
    "contactForm.sendViaWhatsApp": "Send via WhatsApp",
    "contactForm.sending": "Opening...",
    "contactForm.whatsappOpened": "WhatsApp Opened!",
    "contactForm.whatsappMessage": "Your message has been prepared in WhatsApp. Please send it to complete your inquiry.",
    "contactForm.sendAnother": "Send Another Message",
    "contactForm.whatsappNote": "Clicking the button will open WhatsApp with your message",
    
    // Events FAQ
    "eventsFAQ.label": "FAQ",
    "eventsFAQ.title": "Frequently Asked Questions",
    "eventsFAQ.description": "Find answers to common questions about birthday parties and events at Baby World.",
    "eventsFAQ.q1": "How far in advance should I book a birthday party?",
    "eventsFAQ.a1": "We recommend booking at least 7 days in advance to ensure your preferred date and time slot are available. For peak seasons (holidays, weekends), booking 2 weeks ahead is advisable.",
    "eventsFAQ.q2": "Can I bring my own cake and food?",
    "eventsFAQ.a2": "Yes! You are welcome to bring your own birthday cake. For other food items, please coordinate with our team beforehand. We can also help arrange catering from trusted vendors.",
    "eventsFAQ.q3": "What is the refund and cancellation policy?",
    "eventsFAQ.a3": "Cancellations made 48 hours before the event are eligible for a full refund. Cancellations within 48 hours will receive a 50% refund or the option to reschedule within 30 days.",
    "eventsFAQ.q4": "How many guests can attend a birthday party?",
    "eventsFAQ.a4": "Our packages accommodate different group sizes. Basic packages allow up to 15 children, Premium up to 25, and Grand/Custom events can host 30+ children. Additional guests can be added for an extra fee.",
    "eventsFAQ.q5": "Are parents allowed to stay during the party?",
    "eventsFAQ.a5": "Absolutely! Parents and guardians are welcome to stay throughout the event. We provide comfortable seating areas for adults to relax while supervising their children.",
    "eventsFAQ.q6": "What decorations are included in the packages?",
    "eventsFAQ.a6": "Basic packages include standard balloons and banners. Premium packages offer themed decorations with photo backdrop. Grand packages provide fully customized theme setups with premium decorations.",
    "eventsFAQ.moreQuestions": "Have more questions?",
    "eventsFAQ.contactUs": "Contact us",
    
    // Promo Banner
    "promo.badge": "🎈 Eid Special!",
    "promo.message": "Book birthday parties for Eid holidays – Get 15% off!",
    "promo.validUntil": "Valid until Apr 15",
    "promo.cta": "Book Now",
    
    // Footer
    "footer.description": "A safe, hygienic, and joyful indoor playground for children aged 1–10 years. Where kids learn & play in a supervised, nurturing environment.",
    "footer.quickLinks": "Quick Links",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.ageRange": "Ages 1–10 Years",
  },
  bn: {
    // Navigation
    "nav.home": "হোম",
    "nav.about": "আমাদের সম্পর্কে",
    "nav.pricing": "প্লে ও বুকিং",
    "nav.booking": "বুকিং",
    "nav.events": "জন্মদিন ও ইভেন্ট",
    "nav.contact": "যোগাযোগ",
    "nav.bookVisit": "ভিজিট বুক করুন",
    
    // Hero Section
    "hero.badge": "১–১০ বছর বয়সী শিশুদের জন্য",
    "hero.title1": "যেখানে শিশুরা",
    "hero.learn": "শেখে",
    "hero.and": "ও",
    "hero.play": "খেলে",
    "hero.description": "১–১০ বছর বয়সী শিশুদের জন্য একটি নিরাপদ, পরিচ্ছন্ন এবং আনন্দদায়ক ইনডোর প্লেগ্রাউন্ড। আপনার ছোট্ট সোনামণিদের আমাদের তত্ত্বাবধানে থাকা পরিবেশে অন্বেষণ, শিক্ষা ও স্মৃতি তৈরি করতে দিন।",
    "hero.safeEnvironment": "নিরাপদ পরিবেশ",
    "hero.hourlyPlay": "ঘণ্টা ভিত্তিক খেলা",
    "hero.viewOptions": "প্লে অপশন দেখুন",
    "hero.birthdayEvents": "জন্মদিন ও ইভেন্ট",
    "hero.learnPlay": "শেখা ও খেলা",
    
    // About Section
    "about.label": "আমাদের সম্পর্কে",
    "about.title": "একটি জায়গা যেখানে",
    "about.titleHighlight": "শেখা আর খেলা একসাথে",
    "about.description": "বেবি ওয়ার্ল্ডে আমরা বিশ্বাস করি প্রতিটি শিশু একটি নিরাপদ, যত্নশীল পরিবেশ পাওয়ার যোগ্য যেখানে তারা অন্বেষণ, আবিষ্কার এবং বেড়ে উঠতে পারে। আমাদের ইনডোর প্লেগ্রাউন্ড খেলার মাধ্যমে শেখাকে উৎসাহিত করতে সুচিন্তিতভাবে ডিজাইন করা হয়েছে।",
    "about.adventureZone": "অ্যাডভেঞ্চার জোন",
    "about.learningCorner": "লার্নিং কর্নার",
    "about.creativeSpace": "ক্রিয়েটিভ স্পেস",
    "about.pretendPlay": "ভান খেলা",
    "about.safeHygienic": "নিরাপদ ও পরিচ্ছন্ন",
    "about.safeHygienicDesc": "নিয়মিত স্যানিটাইজেশন এবং শিশু-নিরাপদ সরঞ্জাম আপনার মনে শান্তি দেয়।",
    "about.trainedStaff": "প্রশিক্ষিত স্টাফ",
    "about.trainedStaffDesc": "আমাদের বন্ধুত্বপূর্ণ টিম সবসময় তত্ত্বাবধান এবং সহায়তা নিশ্চিত করে।",
    "about.ageAppropriate": "বয়স-উপযোগী কার্যক্রম",
    "about.ageAppropriateDesc": "১–১০ বছর বয়সী শিশুদের জন্য বাছাইকৃত প্লে জোন।",
    
    // Pricing Section
    "pricing.label": "প্লে ও মূল্য",
    "pricing.title": "সহজ, স্বচ্ছ মূল্য",
    "pricing.description": "আপনার পরিবারের জন্য সেরা প্লে অপশনটি বেছে নিন। প্রতিটি সেশনে একজন শিশু এবং একজন অভিভাবক অন্তর্ভুক্ত।",
    "pricing.hourlyPlay": "ঘণ্টা ভিত্তিক খেলা",
    "pricing.sessionTitle": "১ ঘণ্টার প্লে সেশন",
    "pricing.sessionDesc": "দ্রুত ভিজিটের জন্য উপযুক্ত। আপনার ছোট্টটির সাথে সব প্লে জোন উপভোগ করুন।",
    "pricing.childGuardian": "১ শিশু + ১ অভিভাবক",
    "pricing.bookSession": "সেশন বুক করুন",
    "pricing.whatsIncluded": "কী অন্তর্ভুক্ত",
    "pricing.inclusion1": "সব প্লে জোনে প্রবেশ",
    "pricing.inclusion2": "তত্ত্বাবধানকৃত পরিবেশ",
    "pricing.inclusion3": "পরিষ্কার ও স্যানিটাইজড সরঞ্জাম",
    "pricing.inclusion4": "অভিভাবকদের জন্য আরামদায়ক আসন",
    "pricing.inclusion5": "এয়ার-কন্ডিশনড সুবিধা",
    "pricing.walkIn": "ওয়াক-ইন সুবিধা আছে",
    "pricing.physicalTickets": "ফিজিক্যাল টিকেট",
    "pricing.physicalDesc": "সরাসরি পেমেন্ট করতে চান? আমাদের রিসেপশনে ফিজিক্যাল টিকেট পাওয়া যায়।",
    "pricing.noBooking": "আগাম বুকিং প্রয়োজন নেই। অপারেটিং আওয়ারে সরাসরি চলে আসুন।",
    "pricing.guidelines": "প্লে জোন নির্দেশিকা",
    "pricing.rule1": "সবার জন্য মোজা আবশ্যক",
    "pricing.rule2": "প্রবেশে হ্যান্ড স্যানিটাইজেশন",
    "pricing.rule3": "বাইরের খাবার অনুমোদিত নয়",
    "pricing.rule4": "অভিভাবককে অবশ্যই থাকতে হবে",
    
    // Booking Section
    "booking.label": "বুকিং",
    "booking.title": "প্লে টাইম বুক করুন",
    "booking.description": "আপনার সুবিধামত তারিখ ও সময় বাছাই করুন। প্রতিটি সেশন ১ ঘণ্টার।",
    "booking.trustBadge": "১–১০ বছর বয়সী শিশুদের জন্য নিরাপদ খেলার পরিবেশ",
    "booking.selectDate": "তারিখ বাছাই করুন",
    "booking.futureDate": "ভবিষ্যতের যেকোনো তারিখ",
    "booking.selectTime": "সময় বাছাই করুন",
    "booking.eachSlot": "প্রতিটি স্লট ১ ঘণ্টা",
    "booking.selectDateFirst": "প্রথমে একটি তারিখ বাছাই করুন",
    "booking.selected": "নির্বাচিত",
    "booking.available": "উপলব্ধ",
    "booking.booked": "বুকড",
    "booking.summary": "বুকিং সামারি",
    "booking.date": "তারিখ",
    "booking.time": "সময়",
    "booking.ticket": "টিকেট",
    "booking.ticketType": "১ শিশু + ১ অভিভাবক",
    "booking.total": "মোট",
    "booking.confirmBooking": "বুকিং নিশ্চিত করুন",
    "booking.selectDateTime": "তারিখ ও সময় বাছাই করুন",
    "booking.paymentNote": "পেমেন্ট সিস্টেম শীঘ্রই যোগ করা হবে।",
    "booking.book": "বুক করুন",
    "booking.select": "বাছাই করুন",
    "booking.bookViaWhatsApp": "WhatsApp এ বুক করুন",
    "booking.whatsappNote": "বাটনে ক্লিক করলে আপনার বুকিং অনুরোধ WhatsApp এ পাঠানো হবে",
    "booking.groupBooking": "গ্রুপ বুকিং",
    "booking.selectChildren": "শিশু সংখ্যা নির্বাচন করুন (১-৫)",
    "booking.childrenSelectedLabel": "জন শিশু + অভিভাবক নির্বাচিত",
    
    // WhatsApp
    "whatsapp.chat": "WhatsApp",
    "whatsapp.chatWithUs": "WhatsApp এ চ্যাট করুন",
    
    // Testimonials
    "testimonials.label": "অভিভাবকদের মতামত",
    "testimonials.title": "অভিভাবকরা আমাদের সম্পর্কে কী বলেন",
    "testimonials.description": "দেখুন কেন পরিবারগুলো তাদের সন্তানদের খেলা ও উদযাপনের জন্য বেবি ওয়ার্ল্ডকে বিশ্বাস করে।",
    "testimonials.parent1.name": "ফাতিমা রহমান",
    "testimonials.parent1.role": "২ সন্তানের মা",
    "testimonials.parent1.quote": "বেবি ওয়ার্ল্ড আমাদের সাপ্তাহিক ছুটির মজার জায়গা হয়ে গেছে। স্টাফরা অবিশ্বাস্যভাবে যত্নশীল, এবং সবকিছু কতটা পরিষ্কার তা আমার খুব পছন্দ। আমার বাচ্চারা সবসময় দারুণ সময় কাটায়!",
    "testimonials.parent2.name": "কামাল হোসেন",
    "testimonials.parent2.role": "১ সন্তানের বাবা",
    "testimonials.parent2.quote": "আমরা আমার মেয়ের ৪র্থ জন্মদিন এখানে উদযাপন করেছি এবং এটি ছিল জাদুকরী। টিম সবকিছু পেশাদারভাবে সামলেছে। সাজসজ্জা সুন্দর ছিল এবং বাচ্চারা অনেক মজা করেছে!",
    "testimonials.parent3.name": "নুসরাত জাহান",
    "testimonials.parent3.role": "৩ সন্তানের মা",
    "testimonials.parent3.quote": "তিন সন্তানের মা হিসেবে, আমি বয়স-উপযোগী প্লে জোনগুলো সত্যিই পছন্দ করি। আমার প্রতিটি সন্তান তাদের পছন্দের কিছু খুঁজে পায়। প্রশিক্ষিত স্টাফ আমাকে মানসিক শান্তি দেয়।",
    "testimonials.trustStatement": "শত শত সুখী পরিবারের সাথে যোগ দিন যারা বেবি ওয়ার্ল্ডকে বিশ্বাস করে",
    
    // Events Section (Home page preview)
    "events.label": "জন্মদিন ও ইভেন্ট",
    "events.title": "বিশেষ মুহূর্ত উদযাপন করুন",
    "events.description": "বেবি ওয়ার্ল্ডে জন্মদিন উদযাপনের মাধ্যমে স্মৃতিময় মুহূর্ত তৈরি করুন। নিরাপদ, আনন্দময় এবং অবিস্মরণীয় অভিজ্ঞতা আপনার জন্য অপেক্ষা করছে!",
    "events.basicName": "বেসিক সেলিব্রেশন",
    "events.basicDesc": "ঘনিষ্ঠ বন্ধুদের সাথে ছোট আয়োজনের জন্য উপযুক্ত",
    "events.premiumName": "প্রিমিয়াম পার্টি",
    "events.premiumDesc": "সব এক্সট্রা সহ একটি স্মরণীয় উদযাপন",
    "events.grandName": "গ্র্যান্ড ইভেন্ট",
    "events.grandDesc": "সর্বোত্তম জন্মদিনের অভিজ্ঞতা",
    "events.mostPopular": "সবচেয়ে জনপ্রিয়",
    "events.inquireNow": "জানতে চান",
    "events.feature.2hours": "২ ঘণ্টা প্রাইভেট এরিয়া",
    "events.feature.3hours": "৩ ঘণ্টা প্রাইভেট এরিয়া",
    "events.feature.4hours": "৪ ঘণ্টা এক্সক্লুসিভ এরিয়া",
    "events.feature.basicDecor": "বেসিক সাজসজ্জা",
    "events.feature.themeDecor": "থিম সাজসজ্জা",
    "events.feature.customTheme": "কাস্টম থিম সেটআপ",
    "events.feature.playzone": "প্লে জোন অ্যাক্সেস",
    "events.feature.photo": "ফটোগ্রাফি সেশন",
    "events.feature.proPhoto": "প্রফেশনাল ফটোগ্রাফি",
    "events.feature.host": "পার্টি হোস্ট সহায়তা",
    "events.feature.entertainment": "বিনোদন কার্যক্রম",
    "events.feature.coordinator": "ডেডিকেটেড পার্টি কো-অর্ডিনেটর",
    "events.gallery": "সেলিব্রেশন মোমেন্টস",
    "events.viewAll": "সব প্যাকেজ দেখুন",
    
    // Events Page Gallery
    "eventsPage.gallery.label": "ফটো গ্যালারি",
    "eventsPage.gallery.title": "আমাদের উদযাপনের স্মৃতি",
    "eventsPage.gallery.description": "বেবি ওয়ার্ল্ডে আয়োজিত আগের জন্মদিনের পার্টিগুলোর আনন্দ ও উত্তেজনা দেখুন।",
    "eventsPage.gallery.note": "অনুরোধে আরও ছবি পাওয়া যাবে",
    "eventsPage.gallery.clickToView": "ফুলস্ক্রিনে দেখতে ক্লিক করুন",
    
    // Events Page (Dedicated)
    "eventsPage.hero.badge": "জন্মদিন ও বিশেষ ইভেন্ট",
    "eventsPage.hero.title": "অবিস্মরণীয়",
    "eventsPage.hero.titleHighlight": "উদযাপন তৈরি করুন",
    "eventsPage.hero.description": "আপনার সন্তানকে বেবি ওয়ার্ল্ডে একটি চাপমুক্ত, স্মরণীয় জন্মদিন উদযাপন উপহার দিন। আমাদের নিরাপদ, তত্ত্বাবধানে থাকা পরিবেশ শিশুদের জন্য খাঁটি আনন্দ এবং অভিভাবকদের জন্য মানসিক শান্তি নিশ্চিত করে।",
    "eventsPage.hero.cta1": "প্যাকেজ দেখুন",
    "eventsPage.hero.cta2": "বুকিং অনুরোধ",
    "eventsPage.packages.label": "ইভেন্ট প্যাকেজ",
    "eventsPage.packages.title": "আপনার উদযাপনের ধরন বেছে নিন",
    "eventsPage.packages.description": "আপনার সন্তানের বিশেষ দিনের জন্য উপযুক্ত প্যাকেজ নির্বাচন করুন। প্রতিটি প্যাকেজে আমাদের নিরাপদ, পরিচ্ছন্ন পরিবেশে তত্ত্বাবধানে খেলা অন্তর্ভুক্ত।",
    "eventsPage.packages.duration": "সময়কাল",
    "eventsPage.packages.ageRange": "১–১০ বছর বয়সী",
    "eventsPage.packages.selectPackage": "প্যাকেজ নির্বাচন",
    "eventsPage.packages.selectedPackage": "নির্বাচিত",
    "eventsPage.packages.startingFrom": "থেকে শুরু",
    "eventsPage.packages.price.basic": "৳৫,০০০",
    "eventsPage.packages.price.premium": "৳৮,৫০০",
    "eventsPage.packages.price.grand": "৳১৫,০০০",
    "eventsPage.packages.price.custom": "৳২০,০০০+",
    "eventsPage.packages.priceNote": "চূড়ান্ত মূল্য চাহিদা অনুযায়ী",
    "eventsPage.packages.customName": "কাস্টম ইভেন্ট",
    "eventsPage.packages.customDesc": "আপনার বিশেষ চাহিদা অনুযায়ী",
    "eventsPage.packages.feature.5hours": "৫+ ঘণ্টা এক্সক্লুসিভ এরিয়া",
    "eventsPage.packages.feature.fullCustom": "সম্পূর্ণ কাস্টম সেটআপ",
    "eventsPage.packages.feature.catering": "ক্যাটারিং সমন্বয়",
    "eventsPage.packages.feature.vip": "VIP অভিজ্ঞতা",
    "eventsPage.booking.label": "আপনার ইভেন্ট বুক করুন",
    "eventsPage.booking.title": "ইভেন্ট বুকিং অনুরোধ",
    "eventsPage.booking.description": "নিচের ফর্মটি পূরণ করুন এবং আমাদের টিম বিস্তারিত ও উপলব্ধতা নিশ্চিত করতে আপনার সাথে যোগাযোগ করবে।",
    "eventsPage.booking.step1": "ইভেন্টের ধরন",
    "eventsPage.booking.step2": "প্যাকেজ",
    "eventsPage.booking.step3": "পছন্দের তারিখ",
    "eventsPage.booking.step4": "শিশুর বয়স",
    "eventsPage.booking.step5": "যোগাযোগের তথ্য",
    "eventsPage.booking.eventTypeBirthday": "জন্মদিনের পার্টি",
    "eventsPage.booking.eventTypeOther": "অন্যান্য ইভেন্ট",
    "eventsPage.booking.selectEventType": "আপনি কোন ধরনের ইভেন্ট পরিকল্পনা করছেন?",
    "eventsPage.booking.selectPackageStep": "আপনার পছন্দের প্যাকেজ নির্বাচন করুন",
    "eventsPage.booking.selectDateStep": "আপনার পছন্দের তারিখ বেছে নিন",
    "eventsPage.booking.ageGroup1": "১–৩ বছর",
    "eventsPage.booking.ageGroup2": "৪–৬ বছর",
    "eventsPage.booking.ageGroup3": "৭–১০ বছর",
    "eventsPage.booking.selectAgeGroup": "আপনার সন্তানের বয়স গ্রুপ নির্বাচন করুন",
    "eventsPage.booking.parentName": "অভিভাবকের নাম",
    "eventsPage.booking.parentPhone": "ফোন নম্বর",
    "eventsPage.booking.parentNamePlaceholder": "আপনার পুরো নাম লিখুন",
    "eventsPage.booking.parentPhonePlaceholder": "আপনার ফোন নম্বর লিখুন",
    "eventsPage.booking.next": "পরবর্তী",
    "eventsPage.booking.back": "পেছনে",
    "eventsPage.booking.submit": "অনুরোধ জমা দিন",
    "eventsPage.booking.submitting": "জমা হচ্ছে...",
    "eventsPage.booking.confirmNote": "আমাদের টিম বিস্তারিত নিশ্চিত করতে আপনার সাথে যোগাযোগ করবে",
    "eventsPage.booking.successTitle": "অনুরোধ জমা হয়েছে!",
    "eventsPage.booking.successMessage": "আপনার আগ্রহের জন্য ধন্যবাদ। আমাদের টিম ২৪ ঘণ্টার মধ্যে আপনার ইভেন্টের বিস্তারিত নিশ্চিত করতে যোগাযোগ করবে।",
    "eventsPage.booking.newRequest": "নতুন অনুরোধ জমা দিন",
    "eventsPage.trust.title": "বেবি ওয়ার্ল্ডে কেন উদযাপন করবেন?",
    "eventsPage.trust.description": "আপনার সন্তানের নিরাপত্তা ও সুখ আমাদের সর্বোচ্চ অগ্রাধিকার।",
    
    // Trust Section
    "trust.label": "বিশ্বাস ও নিরাপত্তা",
    "trust.title": "আপনার সন্তানের নিরাপত্তা আমাদের অগ্রাধিকার",
    "trust.description": "আমরা বুঝি যে অভিভাবক হিসেবে আপনার সন্তানের কল্যাণের চেয়ে বেশি কিছু গুরুত্বপূর্ণ নয়। তাই আমরা বেবি ওয়ার্ল্ডকে নিরাপত্তাকে মূল ভিত্তি করে তৈরি করেছি।",
    "trust.safePlay": "নিরাপদ খেলার পরিবেশ",
    "trust.safePlayDesc": "নরম, শিশু-বান্ধব সরঞ্জাম যেখানে গোলাকার প্রান্ত এবং সর্বত্র প্যাডেড সারফেস রয়েছে।",
    "trust.trainedStaff": "প্রশিক্ষিত স্টাফ",
    "trust.trainedStaffDesc": "আমাদের টিম শিশু নিরাপত্তা এবং ফার্স্ট এইডে প্রশিক্ষিত, সবসময় তত্ত্বাবধান নিশ্চিত করে।",
    "trust.childFriendly": "শিশু-বান্ধব সরঞ্জাম",
    "trust.childFriendlyDesc": "১–১০ বছর বয়সী শিশুদের জন্য ডিজাইন করা বয়স-উপযোগী খেলার কাঠামো।",
    "trust.cleanHygienic": "পরিষ্কার ও পরিচ্ছন্ন",
    "trust.cleanHygienicDesc": "সব সরঞ্জামের নিয়মিত স্যানিটাইজেশন এবং এয়ার-কন্ডিশনড, ভালো বায়ু চলাচলের জায়গা।",
    "trust.statement": "\"আমি আমার সন্তানকে এই জায়গায় বিশ্বাস করে রাখতে পারি।\"",
    
    // Contact Section
    "contact.label": "যোগাযোগ করুন",
    "contact.title": "আজই বেবি ওয়ার্ল্ডে আসুন",
    "contact.description": "কোনো প্রশ্ন আছে? আমরা আপনার কথা শুনতে চাই। ফোন, ইমেইল বা সরাসরি আসুন।",
    "contact.phone": "ফোন",
    "contact.email": "ইমেইল",
    "contact.address": "ঠিকানা",
    "contact.addressLine1": "২৭/বি, জান্নাত টাওয়ার (লিফট #৩)",
    "contact.addressLine2": "লালবাগ, ঢাকা ১২১১",
    "contact.hours": "খোলার সময়",
    "contact.hoursLine1": "শনিবার - বৃহস্পতিবার: সকাল ১০:০০ – রাত ৯:০০",
    "contact.hoursLine2": "শুক্রবার: বিকাল ৩:০০ – রাত ৯:০০",
    "contact.getDirections": "দিকনির্দেশনা নিন",
    "contact.mapComingSoon": "ইন্টারেক্টিভ ম্যাপ শীঘ্রই আসছে",
    "contact.findUs": "আমাদের খুঁজুন",
    "contact.parking": "পার্কিং",
    "contact.parkingInfo": "কাছাকাছি রাস্তায় পার্কিং আছে",
    "contact.publicTransport": "গণপরিবহন",
    "contact.transportInfo": "লালবাগ বাস স্ট্যান্ডের কাছে",
    "contact.landmark": "ল্যান্ডমার্ক",
    "contact.landmarkInfo": "জান্নাত টাওয়ার, লালবাগ কেল্লার কাছে",
    
    // Contact Form
    "contactForm.title": "আমাদের মেসেজ পাঠান",
    "contactForm.whatsappDescription": "ফর্মটি পূরণ করুন এবং সরাসরি WhatsApp এ আমাদের মেসেজ পাঠান।",
    "contactForm.name": "আপনার নাম",
    "contactForm.namePlaceholder": "আপনার পুরো নাম লিখুন",
    "contactForm.phone": "ফোন নম্বর",
    "contactForm.phonePlaceholder": "আপনার ফোন নম্বর লিখুন",
    "contactForm.email": "ইমেইল (ঐচ্ছিক)",
    "contactForm.emailPlaceholder": "আপনার ইমেইল ঠিকানা লিখুন",
    "contactForm.message": "আপনার বার্তা",
    "contactForm.messagePlaceholder": "আমরা কীভাবে আপনাকে সাহায্য করতে পারি?",
    "contactForm.sendViaWhatsApp": "WhatsApp এ পাঠান",
    "contactForm.sending": "খুলছে...",
    "contactForm.whatsappOpened": "WhatsApp খোলা হয়েছে!",
    "contactForm.whatsappMessage": "আপনার মেসেজ WhatsApp এ প্রস্তুত করা হয়েছে। অনুগ্রহ করে পাঠান বাটনে ক্লিক করুন।",
    "contactForm.sendAnother": "আরেকটি মেসেজ পাঠান",
    "contactForm.whatsappNote": "বাটনে ক্লিক করলে আপনার মেসেজ সহ WhatsApp খুলবে",
    
    // Events FAQ
    "eventsFAQ.label": "প্রশ্নোত্তর",
    "eventsFAQ.title": "সচরাচর জিজ্ঞাসিত প্রশ্ন",
    "eventsFAQ.description": "বেবি ওয়ার্ল্ডে জন্মদিনের পার্টি এবং ইভেন্ট সম্পর্কে সাধারণ প্রশ্নের উত্তর খুঁজুন।",
    "eventsFAQ.q1": "জন্মদিনের পার্টি কতদিন আগে বুক করতে হবে?",
    "eventsFAQ.a1": "আমরা আপনার পছন্দের তারিখ ও সময় নিশ্চিত করতে কমপক্ষে ৭ দিন আগে বুকিং করার পরামর্শ দিই। ছুটির দিন বা সাপ্তাহিক ছুটিতে ২ সপ্তাহ আগে বুকিং করা ভালো।",
    "eventsFAQ.q2": "আমি কি নিজের কেক ও খাবার আনতে পারব?",
    "eventsFAQ.a2": "হ্যাঁ! আপনি নিজের জন্মদিনের কেক আনতে পারবেন। অন্যান্য খাবারের জন্য আমাদের টিমের সাথে আগে থেকে সমন্বয় করুন। আমরা বিশ্বস্ত ক্যাটারিং ব্যবস্থাও করতে পারি।",
    "eventsFAQ.q3": "রিফান্ড ও বাতিল নীতিমালা কী?",
    "eventsFAQ.a3": "ইভেন্টের ৪৮ ঘণ্টা আগে বাতিল করলে পুরো রিফান্ড পাবেন। ৪৮ ঘণ্টার মধ্যে বাতিল করলে ৫০% রিফান্ড বা ৩০ দিনের মধ্যে পুনঃনির্ধারণের সুযোগ থাকবে।",
    "eventsFAQ.q4": "একটি জন্মদিনের পার্টিতে কতজন অতিথি আসতে পারবে?",
    "eventsFAQ.a4": "আমাদের প্যাকেজগুলো বিভিন্ন আকারের গ্রুপের জন্য। বেসিক প্যাকেজে ১৫ জন শিশু, প্রিমিয়ামে ২৫ জন এবং গ্র্যান্ড/কাস্টম ইভেন্টে ৩০+ শিশু থাকতে পারে। অতিরিক্ত অতিথির জন্য আলাদা ফি প্রযোজ্য।",
    "eventsFAQ.q5": "পার্টি চলাকালীন বাবা-মা থাকতে পারবেন কি?",
    "eventsFAQ.a5": "অবশ্যই! বাবা-মা ও অভিভাবকরা পুরো ইভেন্ট জুড়ে থাকতে পারবেন। আমরা বড়দের জন্য আরামদায়ক বসার জায়গা প্রদান করি যেখানে তারা বিশ্রাম নিতে পারবেন।",
    "eventsFAQ.q6": "প্যাকেজে কী কী সাজসজ্জা অন্তর্ভুক্ত?",
    "eventsFAQ.a6": "বেসিক প্যাকেজে সাধারণ বেলুন ও ব্যানার থাকে। প্রিমিয়ামে থিম অনুযায়ী সাজসজ্জা ও ফটো ব্যাকড্রপ থাকে। গ্র্যান্ড প্যাকেজে প্রিমিয়াম সাজসজ্জা সহ সম্পূর্ণ কাস্টম থিম সেটআপ থাকে।",
    "eventsFAQ.moreQuestions": "আরও প্রশ্ন আছে?",
    "eventsFAQ.contactUs": "যোগাযোগ করুন",
    
    // Promo Banner
    "promo.badge": "🎈 ঈদ স্পেশাল!",
    "promo.message": "ঈদের ছুটিতে জন্মদিনের পার্টি বুক করুন – ১৫% ছাড় পান!",
    "promo.validUntil": "১৫ এপ্রিল পর্যন্ত",
    "promo.cta": "এখনই বুক করুন",
    
    // Footer
    "footer.description": "১–১০ বছর বয়সী শিশুদের জন্য একটি নিরাপদ, পরিচ্ছন্ন এবং আনন্দদায়ক ইনডোর প্লেগ্রাউন্ড। যেখানে শিশুরা তত্ত্বাবধানে থাকা পরিবেশে শেখে ও খেলে।",
    "footer.quickLinks": "দ্রুত লিংক",
    "footer.contact": "যোগাযোগ",
    "footer.rights": "সর্বস্বত্ব সংরক্ষিত।",
    "footer.ageRange": "১–১০ বছর বয়সী",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div className={language === "bn" ? "font-bangla" : ""}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
